# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormSplitter.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class ModifySaveAs(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(696, 498)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter_2 = QtWidgets.QSplitter(Form)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frame = QtWidgets.QFrame(self.splitter)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.splitter)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.splitter.setSizes([200, 200])
        self.frame_3 = QtWidgets.QFrame(self.splitter_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout.addWidget(self.splitter_2)
        self.splitter_2.setSizes([300, 200])

        self.Ui_frame()
        self.Ui_frame2()
        self.Ui_frame3()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))

    def Ui_frame(self):
        self.form = QtWidgets.QFormLayout(self.frame)

        self.lineedit_basefile = QtWidgets.QLineEdit()
        self.form.addRow("基准文件", self.lineedit_basefile)

        self.check_restart = QtWidgets.QCheckBox("续算")
        self.form.addRow("Restart", self.check_restart)

        self.lineedit_beta = QtWidgets.QLineEdit()
        self.form.addRow("侧滑角", self.lineedit_beta)

        self.lineedit_alph = QtWidgets.QLineEdit()
        self.form.addRow("攻角", self.lineedit_alph)

        self.radio_altitude = QtWidgets.QRadioButton("海拔高度（m）")
        self.radio_altitude.setChecked(True)
        self.lineedit_altitude = QtWidgets.QLineEdit()
        self.form.addRow(self.radio_altitude, self.lineedit_altitude)

        self.radio_PnT = QtWidgets.QRadioButton("压力和温度")
        self.lineedit_P = QtWidgets.QLineEdit()
        self.lineedit_T = QtWidgets.QLineEdit()
        self.hlayout = QtWidgets.QHBoxLayout()
        self.hlayout.addWidget(self.lineedit_P)
        self.hlayout.addWidget(self.lineedit_T)
        self.form.addRow(self.radio_PnT, self.hlayout)

    def Ui_frame2(self):
        pass

    def Ui_frame3(self):
        pass


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    fram = QtWidgets.QFrame()
    ui = ModifySaveAs()
    ui.setupUi(fram)
    win = QtWidgets.QMainWindow()
    win.setCentralWidget(fram)
    win.resize(600, 400)
    win.show()
    sys.exit(app.exec_())
